---
- name: Add tower inventory
  tower_inventory:
    name: "{{ tower_inventory_name }}"
    organization: Default
    state: present
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_verify_ssl: no

- name: Add tower group
  tower_group:
    name: "{{ ec2_server_group_name }}"
    inventory: "{{ tower_inventory_name }}"
    state: present
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_verify_ssl: no

- name: Add tower host
  tower_host:
    name: "{{ name_prefix + '%02d' | format(item.0 + name_start_index) }}"
    inventory: "{{ tower_inventory_name }}"
    state: present
    tower_host: "{{ tower_host }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_verify_ssl: no
    variables: "ansible_ssh_host: {{ item.1.public_dns_name if ansible_ec2_use_public_ip else item.1.private_ip }}"
  with_indexed_items: "{{ ec2.instances }}"  
  
# https://github.com/ansible/ansible/issues/29149
- name: Find group
  uri:
    url: "https://{{tower_host}}/api/v2/groups/?name={{ ec2_server_group_name}}&&inventory__name={{ tower_inventory_name }}"
    user: "{{tower_username}}"
    password: "{{tower_password}}"
    body_format: json
    force_basic_auth: yes
    validate_certs : no
  register: group_out
  
- debug: var=group_out

- debug: msg="https://{{tower_host}}{{group_out.json.results[0].related.hosts}}"

- name: Associate host with group in inventory
  uri:
    url: "https://{{tower_host}}{{group_out.json.results[0].related.hosts}}"
    method: POST
    body:
      name: "{{ name_prefix + '%02d' | format(item.0 + name_start_index) }}"
    status_code: 201, 204
    user: "{{tower_username}}"
    password: "{{tower_password}}"
    force_basic_auth: yes
    body_format: json
    validate_certs : no
  with_indexed_items: "{{ ec2.instances }}"