---
# tasks file for patch-jboss-eap
- name: Patch JBoss EAP Server
  block:
  - name: Ensure Patch Files Directory Exists
    file:
      path: "{{ jboss_patch_files_directory }}"
      owner: jboss
      group: jboss
      mode: 0644
      state: directory
  
  - name: Copy eap patch file
    copy:
      src: "{{ jboss_eap_patch_artifact_name }}"
      dest: /tmp
      mode: 0600


  # Assumption is that the patch file will be downloaded/saved on the /tmp
  # directory of the JBoss EAP Server prior to running this task
  - name: Copy {{ jboss_eap_patch_artifact_name }} to {{ jboss_patch_files_directory }}
    copy:
      src: "/tmp/{{ jboss_eap_patch_artifact_name }}"
      dest: "{{ jboss_patch_files_directory }}/{{ jboss_eap_patch_artifact_name }}"
      owner: jboss
      group: jboss
      mode: 0644
      remote_src: yes
 
  - name: Apply JBoss EAP Patch
    command: "{{ jboss_eap_home }}/bin/jboss-cli.sh --connect {{ '--command=' ~ cmd | quote }}"
    vars:
      cmd: >-
        patch apply {{ jboss_patch_files_directory }}/{{ jboss_eap_patch_artifact_name }} --override-all 

  - name: shutdown jboss
    command: "{{ jboss_eap_home }}/bin/jboss-cli.sh --connect --command=shutdown "
    notify: start jboss

    #when: name == hostname_vm
