- hosts: all
  become: yes
  
  vars:
    java_packages: java-1.8.0-openjdk
    logstash_version: 7.x
    elasticsearch_version: 7.x
    kibana_version: 7.x
    logstash_monitor_local_syslog: false
    # kibana_elasticsearch_url: http://localhost:9200
    # kibana_server_port: 5601

  roles:
    - geerlingguy.elasticsearch
    - geerlingguy.logstash
    - geerlingguy.kibana
    - tower
    