---
- name: Cleanup 
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
    - vars/tags.yml
    - vars/vpc.yml
    - vars/elb.yml
    
  tasks:
    - ec2_instance_facts:
        region: "{{ vpc_region }}"
        filters: 
          "tag:Application": "{{ application }}"
      register: ec2 

    - ec2:
        region: "{{ vpc_region }}"
        instance_ids: "{{ item.instance_id }}"
        state: absent
        wait: true
      with_items: "{{ ec2.instances }}"

    - ec2_eni_facts:
        filters:
          "tag:Application": "{{ application }}"
      register: eni

    - ec2_eni:
        region: "{{ vpc_region }}"
        eni_id: "{{item.id}}"
        force_detach: yes
        state: absent
      with_items: "{{ eni.network_interfaces }}"


    - ec2_eip_facts:
        filters:
          instance-id: "{{ ec2.instances | map(attribute='instance_id') | list }}"
      register: eips

    - debug: var=eips

    - ec2_eip:
        region: "{{ vpc_region }}"
        public_ip: "{{item.public_ip}}"
        state: absent
      with_items: "{{ eips.addresses }}"
    - ec2_elb_lb:
        region: "{{ vpc_region }}"
        name: "{{load_balancer_name}}"
        state: absent





