---
- name: Reboot
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for SSH to be up
  local_action: wait_for host={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} port=22 state=started delay=15
  become: no