---
# This playbook patches a standalone JBoss EAP server
# The JBoss EAP 6.4 server is deployed using the Ansible JBoss EAP Role
# from this link, i.e. https://github.com/redhat-cop/jboss_eap
- name: Patch Standalone JBoss EAP Server
  hosts: all
  become: true
  remote_user: ec2-user

  roles:
    - patch-jboss-eap                  
