---
- name: VPC | Creating an AWS VPC inside mentioned Region
  ec2_vpc_net:
    name: "{{ vpc_name }}-vpc"
    region: "{{ vpc_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
    tags: 
      Name: "{{ vpc_name }}-vpc"
    state: present    
  register: vpc

- set_fact:
    vpc_id: "{{ vpc.vpc.id }}"

- name: VPC | Create subnet
  ec2_vpc_subnet:
    state: present
    region: "{{ vpc_region }}"
    az: "{{ item.az }}"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.cidr }}"
    resource_tags: "{{ item.resource_tags }}"
    map_public: "{{ item.map_public}}"
  with_items: "{{ vpc_subnets }}"
  register: subnet

- set_fact:
    public_subnet_id:  "{{ subnet.results[0].subnet.id }}"
    web_subnet_id: "{{ subnet.results[1].subnet.id }}"
    db_subnet_id: "{{ subnet.results[2].subnet.id }}"

- name: VPC | Create IGW 
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    region: "{{ vpc_region }}"
    state: present
  register: igw

- name: VPC | Set up route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ vpc_region }}"
    tags:
      Name: "{{ item.name }}"
    subnets: "{{ item.subnet }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  with_items: "{{ subnet_rt }}"
  register: route_table

 # - name: VPC | Write vpc id to file inside the vars directory
 #   shell: echo "{{ vpc.vpc_id }}" > "{{ vpc_name }}-vpc-info.yml"
 #   args:
 #     chdir: aws/vars/

 # - name: VPC | Write public and private subnets id to files inside the vars directory  
 #   shell: echo "{{ item.id }}" > "{{ item.resource_tags.Name }}.yml"
 #   args:
 #     chdir: aws/vars/
 #   with_items: "{{ vpc.subnets }}"

 # - name: VPC | Set the public and private subnet id as facts
 #   set_fact:
 #     vpc_id: "{{ lookup('file', 'aws/vars/' + vpc_name + '-vpc-info.yml') }}"
 #     public_subnet_1: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + public_az_1 + '-public-subnet.yml') }}"
     # public_subnet_2: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + public_az_2 + '-public-subnet.yml') }}"
     # private_subnet: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + private_az + '-private-subnet.yml') }}"
