---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    pvwa_url: "https://xxx.xxx.xxx.xxx"

    cyberark_app_id: "APP_Ansible"
    cyberark_account_name: "{{ vm_hostname }}-{{ vm_username }}"
    cyberark_account_address: "{{ vm_ip }}"
    cyberark_account_username: "{{ vm_username }}"
    cyberark_account_platformid: "UnixSSH"
    cyberark_account_safename: "Ansible"
    cyberark_account_secrettype: "password"
    cyberark_account_secret: "{{ vm_password }}"
    cyberark_account_devicetype: "Operating System"
    cyberark_account_policyid: "UnixSSH"

  tasks:
    - name: Retrieve REST API Service Account for Onboarding to CyberArk
      uri:
       url: "{{pvwa_url}}/AIMWebService/api/Accounts?AppID={{cyberark_app_id}}&Safe=Ansible&Folder=Root&Object=10.246.32.18-Ansible"
       headers:
         Content-Type: "application/json"
       validate_certs: no
       return_content: yes
      register: cyberark_user_response

    #- debug: var=cyberark_user_response

    - name: Set REST API Username to Fact Named cyberark_secret_username
      set_fact:
        cyberark_secret_username: "{{ cyberark_user_response.json.UserName }}"
      no_log: yes

    - name: Set REST API User Password to Fact Named cyberark_secret_userpass
      set_fact:
        cyberark_secret_userpass: "{{ cyberark_user_response.json.Content}}"
      no_log: yes

    - name: Authenticate to CyberArk Web Services
      cyberark_authentication:
        api_base_url: "{{ pvwa_url }}"
        validate_certs: no
        username: "{{ cyberark_secret_username }}"
        password: "{{ cyberark_secret_userpass }}"

    - name: Set CyberArk Authn Token to Fact Named cyberark_authn_token
      set_fact:
        cyberark_authn_token: "{{ cyberark_session.token }}"
      no_log: yes

    - name: Onboard User to CyberArk EPV
      uri:
        url: "{{pvwa_url}}/PasswordVault/WebServices/PIMServices.svc/Account"
        headers:
          Content-Type: application/json
          Authorization: "{{ cyberark_authn_token }}"
        method: POST
        status_code: 201
        body_format: json
        validate_certs: no
        timeout: 120
        body: "{{ lookup('template', 'templates/onboard_user.json.j2') }}"
      register: cyberark_account_response

    - debug: var=cyberark_account_response
